version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: nearbyhappenings-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: always

  frontend:
    build: 
      context: ./Frontend
      args:
        VITE_API_URL: http://65.0.45.151:5000/nearby-happenings
    container_name: nearbyhappenings-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always