deploy:
  needs: build

  runs-on: ubuntu-latest

  if: github.ref == 'refs/heads/main'

  steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          cd ~/NearbyHappenings

          git pull origin main

          docker compose down

          docker compose build

          docker compose up -d