name: Nearby Happenings CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd Backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd Frontend
          npm install

      - name: Build Frontend
        run: |
          cd Frontend
          npm run build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/NearbyHappenings

            git pull origin main

            docker compose down

            docker compose build

            docker compose up -d