name: Nearby Happenings CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VITE_API_URL: http://${{ secrets.EC2_HOST }}:5000/nearby-happenings
  FRONTEND_URL: http://${{ secrets.EC2_HOST }}:5173

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd Backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd Frontend
          npm install

      - name: Build Frontend
        run: |
          cd Frontend
          npm run build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            export VITE_API_URL="http://${{ secrets.EC2_HOST }}:5000/nearby-happenings"
            export FRONTEND_URL="http://${{ secrets.EC2_HOST }}:5173"

            cd ~/NearbyHappenings

            git fetch origin
            git reset --hard origin/main
            git log --oneline -1

            docker compose down
            docker compose up -d --build

            docker compose ps